----------------------------------------------------
-- CREATING TABLES
----------------------------------------------------
CREATE TABLE STATION(
  ID NUMBER,
  NAME VARCHAR2(50)
);

CREATE TABLE TRAIN(
  ID NUMBER,
  NAME VARCHAR2(100),
  DEPART_STN NUMBER,
  DEPART_TIME VARCHAR2(10),
  ARRV_STN NUMBER,
  ARRV_TIME VARCHAR2(10),
  TICKETS NUMBER,
  BOOKED NUMBER,
  FARE NUMBER,
  DAYS NUMBER
);

CREATE TABLE DAY_OF_JOURNEY(
  ID NUMBER,
  TRAIN_ID NUMBER,
  DEPART_DAY VARCHAR2(10),
  ARRV_DAY VARCHAR2(10)
);

CREATE TABLE STOPAGE(
  ID NUMBER,
  TRAIN_ID NUMBER,
  STATION_ID NUMBER,
  STATION_TIME VARCHAR2(20)
);

CREATE TABLE BOOKING(
  ID NUMBER,
  TRAIN_ID NUMBER,
  DEPART_STN NUMBER,
  ARRV_STN NUMBER,
  DEPART_DATE DATE,
  ARRV_DATE DATE,
  NAME VARCHAR2(50),
  AGE NUMBER
);

----------------------------------------------------
-- CONTRAINTS
----------------------------------------------------

ALTER TABLE STATION ADD CONSTRAINT STATION_PKEY PRIMARY KEY(ID);

ALTER TABLE TRAIN ADD CONSTRAINT TRAIN_PKEY PRIMARY KEY(ID);

ALTER TABLE TRAIN ADD CONSTRAINT DEPART_STN_FKEY FOREIGN KEY(DEPART_STN) REFERENCES STATION(ID);

ALTER TABLE TRAIN ADD CONSTRAINT ARRV_STN_FKEY FOREIGN KEY(ARRV_STN) REFERENCES STATION(ID);

ALTER TABLE DAY_OF_JOURNEY ADD CONSTRAINT DAY_OF_JOURNEY_PKEY PRIMARY KEY(ID);

ALTER TABLE DAY_OF_JOURNEY ADD CONSTRAINT DAY_OF_JOURNEY_TRAIN_FKEY FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN(ID);

ALTER TABLE STOPAGE ADD CONSTRAINT STOPAGE_PKEY PRIMARY KEY(ID);

ALTER TABLE STOPAGE ADD CONSTRAINT TRAIN_ID_FKEY FOREIGN KEY(TRAIN_ID) REFERENCES TRAIN(ID);

ALTER TABLE STOPAGE ADD CONSTRAINT STATION_ID_FKEY FOREIGN KEY(STATION_ID) REFERENCES STATION(ID);

----------------------------------------------------
-- SEQUENCES
----------------------------------------------------

CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;