----------------------------------------------------
-- DROPPING CONSTRAINTS
----------------------------------------------------

ALTER TABLE TRAIN DROP CONSTRAINT DEPART_STN_FKEY;

ALTER TABLE TRAIN DROP CONSTRAINT ARRV_STN_FKEY;

ALTER TABLE STOPAGE DROP CONSTRAINT TRAIN_ID_FKEY;

ALTER TABLE STOPAGE DROP CONSTRAINT STATION_ID_FKEY;

ALTER TABLE DAY_OF_JOURNEY DROP CONSTRAINT DAY_OF_JOURNEY_TRAIN_FKEY;

ALTER TABLE STATION DROP CONSTRAINT STATION_PKEY;

ALTER TABLE TRAIN DROP CONSTRAINT TRAIN_PKEY;

ALTER TABLE DAY_OF_JOURNEY DROP CONSTRAINT DAY_OF_JOURNEY_PKEY;

ALTER TABLE STOPAGE DROP CONSTRAINT STOPAGE_PKEY;

DROP SEQUENCE BOOKING_SEQ;

----------------------------------------------------
-- DROPPING TABLES
----------------------------------------------------

DROP TABLE STATION;

DROP TABLE TRAIN;

DROP TABLE DAY_OF_JOURNEY;

DROP TABLE STOPAGE;

DROP TABLE BOOKING;